; PlatformIO Project Configuration File

[env:heltec_wifi_lora_32_V3]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino
monitor_speed = 115200
monitor_filters = send_on_enter
lib_deps =
  jgromes/RadioLib@^7.5.0
  avinabmalla/ESP32_BleSerial@^3.0.0
  rweather/Crypto@^0.4.0
  https://github.com/roloran/SchnorrSig
  https://github.com/roloran/Unishox_Arduino_lib

[env:heltec_wifi_lora_32_V4]
platform = espressif32
board = heltec_wifi_lora_32_V3 ; no newer model available yet
board_build.mcu = esp32s3
framework = arduino
build_flags = 
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
monitor_speed = 115200
monitor_filters = send_on_enter
lib_deps =
  jgromes/RadioLib@^7.5.0
  avinabmalla/ESP32_BleSerial@^3.0.0
  rweather/Crypto@^0.4.0
  https://github.com/roloran/SchnorrSig
  https://github.com/roloran/Unishox_Arduino_lib

[env:heltec_mesh_node_t114_V20]
platform = nordicnrf52
board = nrf52840_dk_adafruit
board_build.mcu = nrf52840
board_build.output = uf2
framework = arduino
platform_packages =
  framework-arduinoadafruitnrf52
build_flags =
  -DRADIOLIB_TONE_UNSUPPORTED
  -DUSE_NRF52
monitor_speed = 115200
monitor_filters = send_on_enter
lib_deps =
  jgromes/RadioLib@^7.5.0
  rweather/Crypto@^0.4.0
  https://github.com/roloran/SchnorrSig
  https://github.com/roloran/Unishox_Arduino_lib

[env:rak_wisblock_4631]
platform = nordicnrf52
board = nrf52840_dk_adafruit
board_build.mcu = nrf52840
board_build.output = uf2
framework = arduino
platform_packages =
  framework-arduinoadafruitnrf52
build_flags =
  -DRADIOLIB_TONE_UNSUPPORTED
  -DUSE_NRF52
  -DUSE_RAK4631 
  -DUSE_DIO2_AS_RF_SWITCH_1262
monitor_speed = 115200
monitor_filters = send_on_enter
lib_deps =
  jgromes/RadioLib@^7.5.0
  rweather/Crypto@^0.4.0
  https://github.com/roloran/SchnorrSig
  https://github.com/roloran/Unishox_Arduino_lib

[env:roloran_dual_channel_2025]
platform = espressif32 @ 6.10.0
board = upesy_wroom
framework = arduino
board_build.partitions = partitions_dual_2025.csv
build_flags =
  -DUSE_ROLORAN_BOARD_V2025
monitor_speed = 115200
monitor_filters = send_on_enter
lib_deps = 
	jgromes/RadioLib@^7.5.0
	rweather/Crypto@^0.4.0
	https://github.com/roloran/SchnorrSig
	https://github.com/roloran/Unishox_Arduino_lib
  rweather/Crypto@^0.4.0
  https://github.com/roloran/SchnorrSig
  https://github.com/roloran/Unishox_Arduino_lib

; EOF