#ifndef _RDCP_MODEM_MBEDTLS_
#define _RDCP_MODEM_MBEDTLS_

#if defined(USE_NRF52)
#define MBEDTLS_AES_C
#define MBEDTLS_BIGNUM_C
#define MBEDTLS_CTR_DRBG_C
#define MBEDTLS_ECP_C
#define MBEDTLS_ECP_CURVE_LIST
#define MBEDTLS_ECP_DP_SECP256R1_ENABLED
#define MBEDTLS_ECP_NIST_OPTIM
#define MBEDTLS_ENTROPY_C
#define MBEDTLS_ENTROPY_HARDWARE_ALT
#define MBEDTLS_MD5_C
#define MBEDTLS_MD_C
#define MBEDTLS_MD_CAN_MD5
#define MBEDTLS_MD_CAN_RIPEMD160
#define MBEDTLS_MD_CAN_SHA1
#define MBEDTLS_MD_CAN_SHA256
#define MBEDTLS_MD_CAN_SHA3_256
#define MBEDTLS_MD_CAN_SHA512
#define MBEDTLS_MD_WRAP_C
#define MBEDTLS_NO_PLATFORM_ENTROPY
#define MBEDTLS_PLATFORM_C
#define MBEDTLS_RIPEMD160_C
#define MBEDTLS_SHA1_C
#define MBEDTLS_SHA256_C
#define MBEDTLS_SHA3_C
#define MBEDTLS_SHA512_C
#define MBEDTLS_TIMING_ALT
#endif

#endif 
/* EOF */