/* rdcp-modem-lora-settings.cpp */

#include <Arduino.h> 
#include "rdcp-modem-lora-settings.h"
#include "rdcp-modem-constants.h"

//< Default LoRa channel settings
lora_channel_config lora_channel[] =
{
    {869.525, BW125, SF7, CR5, SYNCWORD_PRIVATE, TXPOWER_LOW, PL15, SEND_ENABLED, CFEST_MODE_RDCP_V04_868},
    {868.200, BW125, SF7, CR5, SYNCWORD_PRIVATE, TXPOWER_LOW, PL15, SEND_ENABLED, CFEST_MODE_RDCP_V04_868},
    {NO_FREQ, NO_BW, SF7, CR5, SYNCWORD_PRIVATE, TXPOWER_LOW, PL15, SEND_DISABLED, CFEST_MODE_UNKNOWN},
    {NO_FREQ, NO_BW, SF7, CR5, SYNCWORD_PRIVATE, TXPOWER_LOW, PL15, SEND_DISABLED, CFEST_MODE_UNKNOWN},
    {NO_FREQ, NO_BW, SF7, CR5, SYNCWORD_PRIVATE, TXPOWER_LOW, PL15, SEND_DISABLED, CFEST_MODE_UNKNOWN},
    {NO_FREQ, NO_BW, SF7, CR5, SYNCWORD_PRIVATE, TXPOWER_LOW, PL15, SEND_DISABLED, CFEST_MODE_UNKNOWN},
    {NO_FREQ, NO_BW, SF7, CR5, SYNCWORD_PRIVATE, TXPOWER_LOW, PL15, SEND_DISABLED, CFEST_MODE_UNKNOWN},
    {NO_FREQ, NO_BW, SF7, CR5, SYNCWORD_PRIVATE, TXPOWER_LOW, PL15, SEND_DISABLED, CFEST_MODE_UNKNOWN},
    {NO_FREQ, NO_BW, SF7, CR5, SYNCWORD_PRIVATE, TXPOWER_LOW, PL15, SEND_DISABLED, CFEST_MODE_UNKNOWN},
    {NO_FREQ, NO_BW, SF7, CR5, SYNCWORD_PRIVATE, TXPOWER_LOW, PL15, SEND_DISABLED, CFEST_MODE_UNKNOWN},
    {NO_FREQ, NO_BW, SF7, CR5, SYNCWORD_PRIVATE, TXPOWER_LOW, PL15, SEND_DISABLED, CFEST_MODE_UNKNOWN},
    {NO_FREQ, NO_BW, SF7, CR5, SYNCWORD_PRIVATE, TXPOWER_LOW, PL15, SEND_DISABLED, CFEST_MODE_UNKNOWN},
    {NO_FREQ, NO_BW, SF7, CR5, SYNCWORD_PRIVATE, TXPOWER_LOW, PL15, SEND_DISABLED, CFEST_MODE_UNKNOWN},
    {NO_FREQ, NO_BW, SF7, CR5, SYNCWORD_PRIVATE, TXPOWER_LOW, PL15, SEND_DISABLED, CFEST_MODE_UNKNOWN},
    {NO_FREQ, NO_BW, SF7, CR5, SYNCWORD_PRIVATE, TXPOWER_LOW, PL15, SEND_DISABLED, CFEST_MODE_UNKNOWN},
    {NO_FREQ, NO_BW, SF7, CR5, SYNCWORD_PRIVATE, TXPOWER_LOW, PL15, SEND_DISABLED, CFEST_MODE_UNKNOWN}
};

//< Configuration settings for this RDCP device
device_config cfg;

/* EOF rdcp-modem-lora-settings.cpp */